version: '3'

services:

  ################################################################################
  ##### TRAEFIK
  ################################################################################

  proxy:
    image: traefik:v2.0.2
    command:
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    deploy:
       placement:
        constraints:
          - node.role == manager

  ################################################################################
  ##### HELLO WORLD
  ################################################################################

  helloworld:
    image: tutum/hello-world:latest
    networks:
     - proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.helloworld.rule=PathPrefix(`/helloworld`)"
        - "traefik.http.routers.helloworld.entrypoints=web"
        - "traefik.http.services.helloworld.loadbalancer.server.port=80"


  ################################################################################
  ################################################################################
  ##### SWARMPIT
  ################################################################################
  ################################################################################

  swarmpit:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://swarmpitdb:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - agents
      - proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.swarmpit.rule=PathPrefix(`/swarmpit`)"
        - "traefik.http.routers.swarmpit.entrypoints=web"
        - "traefik.http.services.swarmpit.loadbalancer.server.port=8080"
      placement:
        constraints: [node.role == manager]

  swarmpitdb:
    image: couchdb:2.3.0
    volumes:
      - swarmpit_data:/opt/couchdb/data
    networks:
      - agents
      - proxy
    deploy:
      mode: global

  spagent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - agents
    deploy:
      mode: global

volumes:
  swarmpit_data: {}

networks:
  proxy:
    external: true
  agents:
    external: true

