version: '3'

services:

  ################################################################################
  ##### TRAEFIK
  ################################################################################

  proxy:
    image: traefik
    env_file:
      - .env
    command:
      - "--api"
      - "--api.dashboard=true"
      - "--providers.docker"
      - "--entrypoints.http.address=:80"  
    networks:
      - proxy
    ports:
      - 80:80
      - 8088:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.entryPoints=traefik"
        - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.routers.api.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIIK_ADMIN}:${TRAEFIIK_PASSWORD}"
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true